### ISSUE TITLE
Quest 2 Compatibility

### ISSUE THREAD

**Issue by jasondaming** [juchong/QuestNav#1]
Would you expect this to work on a Quest 2 also?

**Comment by juchong** [comment]
This should work with a Quest 2, but you may not see the same performance as a Quest 3 / 3S. The recommended headset for this application is the Quest 3S.

**Comment by jasondaming** [comment]
Could you link the 3D print or whatever you were using to hold it?

**Comment by juchong** [comment]
I'm working on designing a mount that's printable using an FDM printer. I should have something to share in a few days!

**Comment by jasondaming** [comment]
I will still try the quest 2 later 

Here is the 3D Print it worked well:
https://www.asurion.com/connect/tech-tips/how-to-factory-reset-meta-quest-3/
