### ISSUE TITLE
Building requires Meta XR SDK Assets

### ISSUE THREAD

**Issue by MeeperTheGreat99** [juchong/QuestNav#7]
I think you should update the README.md to say you also need to install the Meta XR SDK unity asset from https://assetstore.unity.com/packages/tools/integration/meta-xr-all-in-one-sdk-269657 after installing Unity.

I can create a PR for this, but I figure it's trivial and you probably have further README changes anyway.

Let me know if you want a PR for this.
Thanks

**Comment by juchong** [comment]
Thanks for reaching out! The latest revision of the documentation includes a step for adding the XR SDK to the user's Unity account. :)
