### ISSUE TITLE
Errors occur during build due to missing references for WebSocketSharp and related types.

### ISSUE THREAD

**Issue by NickAnastasoff** [juchong/QuestNav#9]
Error Logs:
Error CS0246: WebSocketSharp not found.
File: Assets/Robot/NetworkTables-CSharp/Nt4Client.cs
Line: 7

Error CS0246: MessageEventArgs not found.
File: Assets/Robot/NetworkTables-CSharp/Nt4Client.cs
Line: 113

Error CS0246: ErrorEventArgs not found.
File: Assets/Robot/NetworkTables-CSharp/Nt4Client.cs
Line: 150

Error CS0246: CloseEventArgs not found.
File: Assets/Robot/NetworkTables-CSharp/Nt4Client.cs
Line: 155

Error CS0246: WebSocket not found.
File: Assets/Robot/NetworkTables-CSharp/Nt4Client.cs
Line: 39

Build fails: "Scripts have compile errors in the editor."
Warning: "Build completed with result 'Unknown'."

Meta > OVR Build > OVR Build APK… doesn’t show up for me so I’m using File > Build Profile > Build with development mode checked. Any help is appreciated!
<img width="1440" alt="Screenshot 2024-12-24 at 11 11 30 AM" src="https://github.com/user-attachments/assets/9845c2bc-6f7e-4c06-87ec-e91934c70696" />

**Comment by ehochstein** [comment]
Check this post to solve the OVR issue: https://www.chiefdelphi.com/t/questnav-the-best-robot-pose-tracking-system-in-frc/476083/170?u=ehochstein

**Comment by NickAnastasoff** [comment]
> This took about 10 minutes, and then afterwards the OVR Build option showed up under the Meta menu.
For me, when I run it, I get
`
Build fails: "Scripts have compile errors in the editor."
Warning: "Build completed with result 'Unknown'."
`
I think the bigger issue is resolving the WebSocketSharp dependency, but i'm not sure how.

**Comment by ehochstein** [comment]
> > This took about 10 minutes, and then afterwards the OVR Build option showed up under the Meta menu.
> 
> 
> 
> For me, when I build it, I get
> 
> `
> 
> Build fails: "Scripts have compile errors in the editor."
> 
> Warning: "Build completed with result 'Unknown'."
> 
> `
> 
> I think the bigger issue is resolving the WebSocketSharp dependency, but i'm not sure how.

I had similar errors on my first import of the project into Unity. To solve these errors, I imported the MessagePack plugin, then closed Unity and imported a **new** QuestNav project. That cleared any WebSocket errors I had.

**Comment by juchong** [comment]
Hi! Like others have mentioned, it sounds like you haven't installed the WebSocket plugin. Be sure to follow step #5: https://github.com/juchong/QuestNav?tab=readme-ov-file#step-5-install-the-messagepack-plugin-for-unity

**Comment by NickAnastasoff** [comment]
All of thats imported, I tried removing it and adding it back, still no luck.

**Comment by juchong** [comment]
The only other thing I can suggest is rebuilding the entire project or trying another PC.

**Comment by NickAnastasoff** [comment]
Just set it up on a windows machine and it worked! Thanks!
